#Problem 32: Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character, replacing a character, or swapping 2 consecutive characters in a string. For simplicity consider only letters from a to z.

def mutate(w):
    print w
    al = 'abcdefghijklmnopqrstuvwxyz'
    alp = [i for i in al]
    rl = ['hello']
    ls = []

    #delete a single char
    for i in range(len(w)):
        temp = [k for k in w]
        temp.remove(temp[i])
        ls.append(''.join(temp))


    #replace a single char
    for i in range(len(w)):
        temp = [k for k in w]
        #print temp
        for j in alp:
            temp[i] = j
            ls.append(''.join(temp))

    #swap two char
    for i in range(len(w)):
        temp = [k for k in w]
        #print temp
        for j in range(len(w)):
            if i != j:
                temp = [k for k in w]
                temp[i],temp[j] = temp[j],temp[i]
                ls.append(''.join(temp))

    #insert a char
    for i in range(len(w)+1):
        temp = [k for k in w]
        #print temp
        for j in alp:
            temp = [k for k in w]
            temp.insert(i,j)
            ls.append(''.join(temp))

            
    #print rl
            
    return ls






print mutate('hello')
